# Generated by Django 5.2.6 on 2025-09-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Crew Member',
                'verbose_name_plural': 'Crew Members',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
